project:
  type: book
  output-dir: docs

book:
  title: "ITSC 2214 - Data Structures and Algorithms - Fall 2023"
  date: "08/21/2023"
  chapters:
    - index.qmd
    - part: "Programming Labs"
      chapters:
        - labs/00_installing_req_software.md
        - labs/01_using_autograder.md
        - labs/02_1l_java_ide_practice-1.md
    - part: "On Computers and Computing"
      chapters:
        - 01_intro_to_cs_dsa.md
        - 02_general_purpose_computers.md
    - part: "Java Generics"
      chapters:
      - 02_1_compilers_types.qmd
    - part: "Algorithmic Analysis"
      chapters:
      - 03_algorithmic_analysis.md
    - part: "Unit Testing"
      chapters:
        - 04_unit_testing.md
        - labs/3L.md
        - 05_writing_junit_tests.md
        - 06_mutation_testing.md
        - 07_list_of_mutators.md
    - part: "Iterative Sorting and Searching"
      chapters:
        - 08_sorting_intro.md
        - 09_comparable_comparator.md
        - 10_bubble_selection_insertion_sort.md
        - 11_linear_search.md
    - part: "Sequential Collections of Data"
      chapters:
        - 12_collections_of_data_intro.qmd
        - 13_operations_on_lists.md
        - 14_implementing_arraylists.md
        - 15_implementing_linkedlists.md
    - part: "Stacks and Queues"
      chapters:
        - 16_stack.md
        - 17_queue.md
    - part: "Recursion"
      chapters:
        - 18_recursion.md
        - 19_binary_search.md
    - part: "Trees and Graphs"
      chapters:
      - 20_trees.qmd
      - 21_graphs.qmd
    - part: "Hashing"
      chapters:
      - 22_hashing.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

website:
  open-graph: true
  reader-mode: true
  repo-url: https://github.com/Charlotte-CCI-ICC/itsc-2214-readings
  repo-actions: [edit, issue]
  navbar:
    search: true
    collapse-level: 0